apiVersion: v1
kind: Service
metadata:
  name: ddos-detection
spec:
  selector:
    module: detection
  type: NodePort
  ports:
  - port: 5060
    nodePort: 31060
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddos-detection
  labels:
    module: detection
spec:
  replicas: 1
  selector:
    matchLabels:
      module: detection
  template:
    metadata:
      labels:
        module: detection
    spec:
      containers:
      - name: ddos-detection
        image: 192.168.56.1:5000/ddos-detection
        imagePullPolicy: Always
        ports:
        - containerPort: 5060
