version: "3.3"
services:
  ddos-detection:
    image: 192.168.56.1:5000/normal-user
    container_name: normal-user
    build:
      context: ..
      dockerfile: deployment/Dockerfile
#    ports:
#    - 5051:5051
    network_mode: "host"