apiVersion: apps/v1
kind: Deployment
metadata:
  name: normal-user
  labels:
    machine: user
spec:
  replicas: 3
  selector:
    matchLabels:
      machine: user
  template:
    metadata:
      labels:
        machine: user
    spec:
      containers:
      - name: normal-user
        image: 192.168.56.1:5000/normal-user
        imagePullPolicy: Always
#        ports:
#        - containerPort: 5051
