apiVersion: apps/v1
kind: Deployment
metadata:
  name: attacker
  labels:
    machine: attacker
spec:
  replicas: 1
  selector:
    matchLabels:
      machine: attacker
  template:
    metadata:
      labels:
        machine: attacker
    spec:
      containers:
      - name: attacker
        image: 192.168.56.1:5000/attacker
        imagePullPolicy: Always
