version: "3.3"
services:
  ddos-detection:
    image: 192.168.56.1:5000/attacker
    container_name: attacker
    build:
      context: ..
      dockerfile: deployment/Dockerfile
#    ports:
#    - 5052:5052
    network_mode: "host"