version: "3.3"
services:
  ddos-detection:
    image: 192.168.56.1:5000/nodeserver
    container_name: nodeserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - 5050:5050
    network_mode: "host"